require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - config.ru
    - bin/**
    - db/schema.rb
    - node_modules/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LineLength:
  Max: 125

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - config.rb
    - spec/**/*

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 8

Naming/VariableNumber:
  Enabled: false

Rails/HelperInstanceVariable:
  Exclude:
    - app/helpers/redcarpet_helper.rb

Rails/OutputSafety:
  Exclude:
    - app/helpers/redcarpet_helper.rb

Rails/Output:
  Exclude:
    - db/seeds.rb

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*_spec.rb'
    - 'spec/system/**/*_spec.rb'

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/MultipleExpectations:
  Max: 5

RSpec/NamedSubject:
  Enabled: true

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 15

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%": ()
    "%i": ()
    "%q": ()
    "%Q": ()
    "%r": "{}"
    "%s": ()
    "%w": ()
    "%W": ()
    "%x": ()

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: percent
