addons:
  postgresql: "9.4"

# addons:
#   postgresql: "11"
#   apt:
#     packages:
#     - postgresql-11
#     - postgresql-client-11

services:
  - postgresql

language: ruby

rvm:
  - 3.0
  - 2.7

jobs:
  allow_failures:
    # - rvm: 3.0

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'

bundler_args: --without production --binstubs --jobs 6 --retry 3

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate

script: bundle exec rake ci
